name: pjenchants
version: ${project.version}
main: net.pajamasoft.pjenchants.PJEnchants
api-version: 1.21.11
authors: [ pajamasoft ]
description: PJ's Custom Enchantments
commands:
  pjenchants:
    description: Main command for PJ Enchants
    usage: /pjenchants
    aliases: [pje]
